### ISSUE TITLE
Issue with imports/circular dependencies on mac

### ISSUE THREAD

**Issue by kratsg** [lorenzennio/pyhf-tutorial#2]
```python
import numpy as np
import pyhf
import matplotlib.pyplot as plt
from bayesian_pyhf import infer, prepare_inference, plotting
import pymc as pm
import corner
import arviz as az
```

which comes with this error

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 4
      2 import pyhf
      3 import matplotlib.pyplot as plt
----> 4 from bayesian_pyhf import infer, prepare_inference, plotting
      5 import pymc as pm
      6 import corner

File ~/pyhf-tutorial-belle2/.pixi/envs/default/lib/python3.12/site-packages/bayesian_pyhf/infer.py:7
      4 import corner
      5 import json
----> 7 import pytensor
      8 from pytensor import tensor as pt
      9 from pytensor.graph.basic import Apply

File ~/pyhf-tutorial-belle2/.pixi/envs/default/lib/python3.12/site-packages/pytensor/__init__.py:118
    114     return as_tensor_variable(x, **kwargs)
    117 # isort: off
--> 118 from pytensor import scalar, tensor
    119 from pytensor.compile import (
    120     In,
    121     Mode,
   (...)
    127     shared,
    128 )
    129 from pytensor.compile.function import function, function_dump

File ~/pyhf-tutorial-belle2/.pixi/envs/default/lib/python3.12/site-packages/pytensor/tensor/__init__.py:103
     99     return len(var.data)
    102 import pytensor.tensor.exceptions
--> 103 import pytensor.tensor.rewriting
    104 from pytensor.gradient import grad, hessian, jacobian
    106 # adds shared-variable constructors

File ~/pyhf-tutorial-belle2/.pixi/envs/default/lib/python3.12/site-packages/pytensor/tensor/rewriting/__init__.py:1
----> 1 import pytensor.tensor.rewriting.basic
      2 import pytensor.tensor.rewriting.blas
      3 import pytensor.tensor.rewriting.blas_c

File ~/pyhf-tutorial-belle2/.pixi/envs/default/lib/python3.12/site-packages/pytensor/tensor/rewriting/basic.py:43
     34 from pytensor.graph.rewriting.basic import (
     35     NodeRewriter,
     36     RemovalNodeRewriter,
   (...)
     40     node_rewriter,
     41 )
     42 from pytensor.graph.rewriting.db import RewriteDatabase
---> 43 from pytensor.raise_op import Assert, CheckAndRaise, assert_op
     44 from pytensor.tensor.basic import (
     45     Alloc,
     46     AllocEmpty,
   (...)
     64     zeros_like,
     65 )
     66 from pytensor.tensor.elemwise import DimShuffle, Elemwise

File ~/pyhf-tutorial-belle2/.pixi/envs/default/lib/python3.12/site-packages/pytensor/raise_op.py:14
     12 from pytensor.link.c.type import Generic
     13 from pytensor.scalar.basic import ScalarType
---> 14 from pytensor.tensor.type import DenseTensorType
     17 class ExceptionType(Generic):
     18     def __eq__(self, other):

File ~/pyhf-tutorial-belle2/.pixi/envs/default/lib/python3.12/site-packages/pytensor/tensor/type.py:801
    796         dtype = config.floatX
    798     return TensorType(dtype=dtype, shape=shape, **kwargs)(name=name)
--> 801 cscalar = TensorType("complex64", ())
    802 zscalar = TensorType("complex128", ())
    803 fscalar = TensorType("float32", ())

File ~/pyhf-tutorial-belle2/.pixi/envs/default/lib/python3.12/site-packages/pytensor/tensor/type.py:105, in TensorType.__init__(self, dtype, shape, name, broadcastable)
    103     self.dtype = config.floatX
    104 else:
--> 105     if np.obj2sctype(dtype) is None:
    106         raise TypeError(f"Invalid dtype: {dtype}")
    108     self.dtype = np.dtype(dtype).name

File ~/pyhf-tutorial-belle2/.pixi/envs/default/lib/python3.12/site-packages/numpy/__init__.py:400, in __getattr__(attr)
    397     raise AttributeError(__former_attrs__[attr], name=None)
    399 if attr in __expired_attributes__:
--> 400     raise AttributeError(
    401         f"`np.{attr}` was removed in the NumPy 2.0 release. "
    402         f"{__expired_attributes__[attr]}",
    403         name=None
    404     )
    406 if attr == "chararray":
    407     warnings.warn(
    408         "`np.chararray` is deprecated and will be removed from "
    409         "the main namespace in the future. Use an array with a string "
    410         "or bytes dtype instead.", DeprecationWarning, stacklevel=2)

AttributeError: `np.obj2sctype` was removed in the NumPy 2.0 release. Use `np.dtype(obj).type` instead.
```

perhaps @matthewfeickert knows how to best resolve this or disentangle it?

**Comment by matthewfeickert** [comment]
It would be helpful to know the environment versions of the the relevant packages here. This doesn't seem to be a circular dependencies issue at all though, but just that the version of PyTensor used here is not NumPy 2.0 compatible.

**Comment by matthewfeickert** [comment]
Yeah, assuming that you are using the `pixi` environment as of a33c9597c9673bba29352c2c78dbc4744401505b then you have `pytensor` `v2.20.0`

https://github.com/lorenzennio/pyhf-tutorial/blob/a33c9597c9673bba29352c2c78dbc4744401505b/pixi.lock#L9730-L9732

which was released on 2024-03-28 and apparently wasn't NumPy 2.0 compatible (they didn't test against the release candidates). You can replicate the error just with installing `numpy` `2.0+` and `pytensor` `v2.20.0`

```console
$ docker run --rm -ti python:3.12 bash
root@8726b02f2132:/# python -m venv venv && . venv/bin/activate && python -m pip install uv
Collecting uv
  Downloading uv-0.4.24-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Downloading uv-0.4.24-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.6/13.6 MB 29.4 MB/s eta 0:00:00
Installing collected packages: uv
Successfully installed uv-0.4.24
(venv) root@8726b02f2132:/# uv pip install 'numpy>=2.0.0' 'pytensor==2.20.0'
Using Python 3.12.7 environment at /venv
Resolved 12 packages in 734ms
   Built minikanren==1.0.3
   Built logical-unification==0.4.6
   Built etuples==0.3.9
   Built cons==0.4.6
Prepared 12 packages in 5.98s
Installed 12 packages in 30ms
 + cons==0.4.6
 + etuples==0.3.9
 + filelock==3.16.1
 + logical-unification==0.4.6
 + minikanren==1.0.3
 + multipledispatch==1.0.0
 + numpy==2.1.2
 + pytensor==2.20.0
 + scipy==1.14.1
 + setuptools==75.2.0
 + toolz==1.0.0
 + typing-extensions==4.12.2
(venv) root@8726b02f2132:/# python -c 'import numpy as np; import pytensor'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/venv/lib/python3.12/site-packages/pytensor/__init__.py", line 118, in <module>
    from pytensor import scalar, tensor
  File "/venv/lib/python3.12/site-packages/pytensor/tensor/__init__.py", line 103, in <module>
    import pytensor.tensor.rewriting
  File "/venv/lib/python3.12/site-packages/pytensor/tensor/rewriting/__init__.py", line 1, in <module>
    import pytensor.tensor.rewriting.basic
  File "/venv/lib/python3.12/site-packages/pytensor/tensor/rewriting/basic.py", line 43, in <module>
    from pytensor.raise_op import Assert, CheckAndRaise, assert_op
  File "/venv/lib/python3.12/site-packages/pytensor/raise_op.py", line 14, in <module>
    from pytensor.tensor.type import DenseTensorType
  File "/venv/lib/python3.12/site-packages/pytensor/tensor/type.py", line 801, in <module>
    cscalar = TensorType("complex64", ())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/pytensor/tensor/type.py", line 105, in __init__
    if np.obj2sctype(dtype) is None:
       ^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/numpy/__init__.py", line 400, in __getattr__
    raise AttributeError(
AttributeError: `np.obj2sctype` was removed in the NumPy 2.0 release. Use `np.dtype(obj).type` instead.
(venv) root@8726b02f2132:/# 
```

The reason being here though is that `pixi` is doing its best to solve the environment and `pytensor` `v2.20.0` doesn't disallow NumPy `v2.x` while the latest `pytensor` (`v2.25.5`) does (it still isn't NumPy 2.0 compatible. :disappointed: )

```console
(venv) root@8726b02f2132:/# uv pip install 'numpy>=2.0.0' 'pytensor==2.25.5'
Using Python 3.12.7 environment at /venv
  × No solution found when resolving dependencies:
  ╰─▶ Because pytensor==2.25.5 depends on numpy>=1.17.0,<2 and you require numpy>=2.0.0, we can conclude that your requirements and pytensor==2.25.5 are incompatible.
      And because you require pytensor==2.25.5, we can conclude that your requirements are unsatisfiable.
```

FWIW, `pytensor` `v2.20.0`'s requirements on NumPy are `numpy>=1.17.0`:

```console
# uv pip install --upgrade --verbose 'numpy>=2.0.0' 'pytensor==2.20.0' &> log.txt && grep 'pytensor==2.20.0' log.txt
DEBUG Adding direct dependency: pytensor==2.20.0
DEBUG Selecting: pytensor==2.20.0 [compatible] (pytensor-2.20.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
DEBUG Adding transitive dependency for pytensor==2.20.0: setuptools>=48.0.0
DEBUG Adding transitive dependency for pytensor==2.20.0: scipy>=0.14
DEBUG Adding transitive dependency for pytensor==2.20.0: numpy>=1.17.0
DEBUG Adding transitive dependency for pytensor==2.20.0: filelock*
DEBUG Adding transitive dependency for pytensor==2.20.0: etuples*
DEBUG Adding transitive dependency for pytensor==2.20.0: logical-unification*
DEBUG Adding transitive dependency for pytensor==2.20.0: minikanren*
DEBUG Adding transitive dependency for pytensor==2.20.0: cons*
DEBUG Adding transitive dependency for pytensor==2.20.0: typing-extensions*
DEBUG Requirement already installed: pytensor==2.20.0
```
